events { worker_connections 2048; }

http {
  upstream onex_node {
    server onexd:8545;
  }

  upstream onex_bridge {
    server onex-bridge:9338;
  }

  server {
    listen 80;
    server_name _;

    location /wallet/ {
      proxy_pass http://onex_bridge/wallet/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /bridge/ {
      proxy_pass http://onex_bridge/bridge/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /rpc {
      proxy_pass http://onex_node;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://onex_node;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }

  server {
    listen 443 ssl;
    server_name _;
    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location /wallet/ {
      proxy_pass http://onex_bridge/wallet/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
    }

    location /bridge/ {
      proxy_pass http://onex_bridge/bridge/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /rpc {
      proxy_pass http://onex_bridge;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
    }

    location / {
      proxy_pass http://onex_node;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
